### ISSUE TITLE
Hey, just wondering if there were assignments for this. Or a syllabus/ overview.

### ISSUE THREAD

**Issue by candywal** [maziarraissi/Applied-Deep-Learning#5]
Hey, just wondering if there were assignments for this. Or a syllabus/ overview. 

Would you recommend a self-learner watch all the videos to learn or some other method?

**Comment by maziarraissi** [comment]
The assignments are in the form of: 1) exploratory data analysis and 2) exploring the source codes of the papers discussed in class. Yes, a self-learner can benefit from watching all the videos.
