### ISSUE TITLE
EfficentNet Lecture Video Question

### ISSUE THREAD

**Issue by karl-gardner** [maziarraissi/Applied-Deep-Learning#7]
Hello Dr. Maziar Raissi, I am a PhD student in Machine Learning and sincerely appreciate you posting these videos online as they are very helpful. I have a small question that is not explained well in the paper and the authors skip over it. In the mnasnet paper, they use an empirical observation that doubling the Latency will increase accuracy by 5%: " for instance, we empirically observed doubling the latency usually brings about 5% relative accuracy gain." and therefore the authors solve for the omega parameter (setting alpha equal to beta) and obtain -0.07 from this empirical observation. However, this observation is only for LATENCY and not for flops or memory as the parameter they were optimizing was LATENCY. In the efficientnet paper the authors describe that they optimized flops instead of latency with an objective function (reward) as the following formula: ACC(m)*[FLOPS(m)/T]^w . With this reward function they use the same value for omega for controlling the trade off between accuracy and flops: "Specifically, we use the same search space as (Tan et al., 2019), and use ACC(m)×[FLOP S(m)/T]^w as the optimization goal, where ACC(m) and F LOPS(m) denote the accuracy and FLOPS of model m, T is the target FLOPS and w=-0.07 is a hyperparameter for controlling the trade-off between accuracy and FLOPS. Here, they use w=-0.07 which is based on the empirical observation from the mnasnet paper that doubling the LATENCY will increase accuracy by 5%. This observation is only for latency and not flops though. So my question is why they can make this assumption that w=-0.07 for flops as well unless this is some sort of guess for the w hyperparameter? Thanks, let me know if you would like me to elaborate on my confusion.

**Comment by maziarraissi** [comment]
You are right! Flops and Latency are different and are at best correlated. Setting w=-0.07 is just a guess and the arguments made in the paper are some intuitive justifications for this guess. Please don't overthink it. Actually, writing the objective function in terms of latency of the target device is more useful in practice and there are some papers that do just that.

**Comment by karl-gardner** [comment]
Hello Dr. Raissi,

I appreciate your response! That makes more sense that it was just an estimated guess. Btw I have cited your github applied deep learning page in my most recent paper applying EfficientNetV2 model (not sure I can actually cite youtube). 

Thanks,

Karl Gardner
